#!/bin/bash
# Generate go2rtc config from cam_capture/cameras.conf
# Usage: ./deploy_scripts/generate_go2rtc_yaml.sh [output_path]

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CAM_CONF="$ROOT_DIR/cam_capture/cameras.conf"
OUT_FILE="${1:-$ROOT_DIR/go2rtc/go2rtc.yaml}"

if [[ ! -f "$CAM_CONF" ]]; then
  echo "ERROR: cameras.conf not found at $CAM_CONF" >&2
  exit 1
fi

# shellcheck source=/dev/null
source "$CAM_CONF"

mkdir -p "$(dirname "$OUT_FILE")"

cat > "$OUT_FILE" <<EOF
# Generated by deploy_scripts/generate_go2rtc_yaml.sh
# No-transcode setup. Streams are republished from RTSP as-is.

api:
  listen: "127.0.0.1:1984"

rtsp:
  listen: "127.0.0.1:8554"

webrtc:
  listen: ":8555"

streams:
  # Live view aliases use main camera streams.
  cam1_main: ${CAM1_MAIN}
  cam2_main: ${CAM2_MAIN}
  cam3_main: ${CAM3_MAIN}
EOF

echo "Generated $OUT_FILE"
